#
# Makefile for ML_SECURITY's common library
#

obj-y			:= common.o tail_data.o module_tools.o


#ifdef example
#ifdef CONFIG_ML_SECURITY
#	obj-y		+=
#else
#	obj-y		+=
#endif



#Append your specialized "common"-config options here, if you *really* want to split our common library into parts. Generally, just compile everything in one piece. Its a common lib after all.
#Each config should represent a feature or a subfeature to be controlled by the defconfig/menuconfig

#obj-$(CONFIG_ML_SEC_COMMON_FTR1) += <file>.o   <folder>/

