#ifndef __MLSEC_SBOX_SCRIPTS_INCLUDE_HOST_LINUX_ATOMIC_H
#define __MLSEC_SBOX_SCRIPTS_INCLUDE_HOST_LINUX_ATOMIC_H

typedef int atomic_t;

#endif /* __MLSEC_SBOX_SCRIPTS_INCLUDE_HOST_LINUX_ATOMIC_H */

