obj-$(CONFIG_TEGRA_SOCTHERM)	+= tegra-soctherm.o
obj-$(CONFIG_TEGRA_AOTAG)	+= aotag.o
obj-$(CONFIG_TEGRA_TJ_THERMAL)	+= tegra_tj_thermal.o
obj-$(CONFIG_TEGRA_KFUSE)	+= tsensor-fuse.o

tegra-soctherm-$(CONFIG_TEGRA_SOCTHERM)		:= soctherm.o
tegra-soctherm-$(CONFIG_ARCH_TEGRA_124_SOC)	+= tegra124-soctherm.o
tegra-soctherm-$(CONFIG_ARCH_TEGRA_132_SOC)	+= tegra132-soctherm.o
tegra-soctherm-$(CONFIG_ARCH_TEGRA_210_SOC)	+= tegra210-soctherm.o
tegra-soctherm-$(CONFIG_ARCH_TEGRA_210_SOC)	+= tegra-core-action.o
tegra-soctherm-$(CONFIG_ARCH_TEGRA_210_SOC)	+= tegra-dfll-action.o
