EXTRA_CFLAGS += -I$(srctree)/../display/drivers/video/tegra/dc
EXTRA_CFLAGS += -I../nvhost/drivers/video/tegra/host
EXTRA_CFLAGS += -I../display/drivers/video/tegra/host
obj-y += sfd.o
obj-y += sfd_t186.o
